project:
  type: website
  output-dir: docs

website:
  title: "StellarStats2023"
  navbar:
    left:
      - href: index.qmd
        text: Schedule
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



